# Generated by Django 5.2.5 on 2025-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=100)),
                ('system_user', models.BooleanField(default=False)),
                ('offered_product', models.CharField(blank=True, choices=[('A', 'Product A'), ('B', 'Product B'), ('C', 'Product C'), ('D', 'Product D'), ('E', 'Product E'), ('F', 'Product F')], max_length=1, null=True)),
                ('potential_market_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('potential_yearly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_action', models.TextField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('comment_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
