# Generated by Django 5.2.5 on 2025-08-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reason_for_roadblock',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Progressing', 'Progressing'), ('On Hold', 'On Hold'), ('Win', 'Win'), ('Lost', 'Lost')], default='Progressing', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='potential_market_share',
            field=models.IntegerField(blank=True, choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='potential_yearly_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
