# Generated by Django 5.2.5 on 2025-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_reason_for_roadblock_client_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reason_for_roadblock',
            field=models.CharField(blank=True, choices=[('Budget freeze', 'Budget freeze'), ('Stakeholder unvailable', 'Stakeholder unvailable'), ('Needs approval', 'Needs approval'), ('Technical issue', 'Technical issue'), ('Resource limitation', 'Resource limitation'), ('Pricing negotiation', 'Pricing negotiation'), ('Project postponed', 'Project postponed')], max_length=50, null=True),
        ),
    ]
